### ISSUE TITLE
Support private registries

### ISSUE THREAD

**Issue by tgruenert** [philpep/imago#1]
First of all: thank your for this project! It may can be the missing link in our deployment chain.
Unfortunately we use various private docker repositories in our projects and this tool doesn't support this yet.

**use case**
I want to check a deployment build out from a private repository for any updates.

**solution**
The tool supports a new command line parameter to specify a Kubernetes registry object, which use the given registry and its credentials to check for any updates.

`docker run --rm -it -u $(id -u) -v ~/.kube/config:/config philpep/imago -n default --registry my-private-reg`

**nice enhancement**
it would be nice to support multiple registries as commadn line paramaters. but i think its nice to have.

If more information needed please feel free to ask.
Thx

**Comment by philpep** [comment]
Hi, thanks for reporting !

imago should be able to works with multiple public and private registries (I tested against docker hub, quay.io and docker private registry).
When image doesn't isn't prefixed by the registry url, imago use docker public registry as default registry, I guess you configured an alternative default registry in docker (or other backend) configuration ?
In this case I think adding a ``--default-registry`` option could handle this, but maybe we can query kubernetes to have this information, I'll have a look.

**Comment by tgruenert** [comment]
Thank you @philpep !
After further testing i can see, information about used registry seem´d to be respected. In my case i get 
`2019/03/10 17:05:11 Unexpected response while requesting https://url.tld/v2/organization/artefact/manifests/0.0.2: 401 Unauthorized`
for an already working deployment.

Deployment uses a docker secret to authenticate at repository. Are you able to give me some hints about failure reasons? The docker secret contains user / password authentication.

**Comment by philpep** [comment]
imago should use secrets if they are defined in ``ImagePullSecrets`` on the deployment / daemonset, do you have one ?

Then I think there's some unhandled cases:

* use of ImagePullSecrets defined in ServiceAccount
* local backend configuration with authentication on kubernetes nodes

Maybe we could add a ``--docker-config /path/to/docker/config.json`` option to handle this.
Also I think adding some log about secrets being used could be worth.

**Comment by tgruenert** [comment]
I tested the simular setup with an other cluster i manage. For this everything is working fine. 
The only difference i see is the registry itself. Nexus 3 works nice, Nexus 2 doesn´t. I am not sure how i will handle this. Upgrading repo is an other topic.

Thank you for this app - i am sure i will use it sometimes.

**Comment by tgruenert** [comment]
sorry, no close, you had some enhancements with this.

**Comment by blairdrummond** [comment]
You can accomplish this my mounting an image pull secret and setting DOCKER_CONFIG to the folder containing its config.json file. Note that I rename the secret data here so that the file name matches up.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: imago
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: imago
        spec:
          restartPolicy: Never
          serviceAccount: imago
          serviceAccountName: imago
          containers:
          - name: imago
            image: philpep/imago
            imagePullPolicy: Always
            args: ["-restart"]
          # Below this line configures private registries
            env:
            - name: DOCKER_CONFIG
              value: /docker
            volumeMounts:
            - mountPath: /docker
              name: docker-config
              readOnly: true
          volumes:
          - name: docker-config
            secret:
              secretName: acr-creds
              optional: false
              items:
              - key: .dockerconfigjson
                path: config.json

```
